name: 'Update Domain List'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 15 * *' # At 10:00 on day-of-month 15

env:
  FOLDER: '${{ github.workspace }}/cloudflare/lists'

permissions: read-all

jobs:
  auto-update:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: write
      pull-requests: write    
    
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3.5.2

      #
      # Fetch domain list
      #
      - name: Fetch Domain List
        working-directory: ${{ env.FOLDER }}
        run: |
          LIST_FNAME="pihole_domain_list.txt"
          curl -sSL https://raw.githubusercontent.com/bongochong/CombinedPrivacyBlockLists/master/NoFormatting/BlacklistedDomains.txt > ${LIST_FNAME}

      #
      # Commit file
      #
      - name: ↗️ Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Update Domain List'
          branch-suffix: timestamp
          commit-message: 'Update Domain List'
          body: ''
